language: node_js
node_js: 
  - "9.11.1"

install:
  - yarn

cache:
  directories:
    - node_modules

script:
  - npm run build

after_success:
  - cd ./build
  - git init
  - git config --global user.name "joname1"
  - git config --global user.email "274158741@qq.com"
  - git add .
  - git commit -m "`curl -s whatthecommit.com/index.txt`"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - dev
env:
  global:
    - GH_REF: github.com/joname1/tech.git